apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: fastapi-app   # Must match Service label
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http        # Must match Service port name
      path: /metrics
      interval: 15s
