name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tag
        id: set_tag
        run: echo "IMAGE_TAG=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build and push frontend image
        run: |
          docker build -t mani0831/myapp-frontend:${{ env.IMAGE_TAG }} ./frontend
          docker push mani0831/myapp-frontend:${{ env.IMAGE_TAG }}

      - name: Build and push backend image
        run: |
          docker build -t mani0831/myapp-backend:${{ env.IMAGE_TAG }} ./backend
          docker push mani0831/myapp-backend:${{ env.IMAGE_TAG }}

      - name: Update Kubernetes Manifests
        run: |
          # Use a tool to replace image tags in YAML files
          sed -i "s|image: .*myapp-frontend.*|image: mani0831/myapp-frontend:${{ env.IMAGE_TAG }}|" k8s/frontend-deployment.yaml
          sed -i "s|image: .*myapp-backend.*|image: mani0831/myapp-backend:${{ env.IMAGE_TAG }}|" k8s/backend-deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add k8s/*.yaml
          git commit -m "ci: Update image tags to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"
          git push
